spring.datasource.url=jdbc:postgresql://localhost:5432/seguridad
spring.datasource.username=DATA_BASE_USER
spring.datasource.password=DATA_BASE_PASSWORD
spring.application.name=security

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto= update

jwt.secret = replace_with_your_own_256_bits_secret
jwt.expiration = 3600
