spring.datasource.url=jdbc:postgresql://localhost:5432/seguridad
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.application.name=security

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto= update

jwt.secret = c1e4e9c0dfc3d662beaf9cea1f02d98e657a46e5a0dec3e9943c29c8c7ad804c
jwt.expiration = 3600
